---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 16.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/radarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "radarr.${SECRET_PRIVATE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        exsistingClaim: radarr-config
      downloads:
        enabled: true
        type: custom
        mountPath: /downloads
        storageClass: nfs
        accessMode: ReadWriteMany
        size: 1Gi
        volumeSpec:
            nfs:
                server: 10.10.0.1
                path: /mnt/media/Downloads
      media:
        enabled: true
        type: custom
        mountPath: /media/Movies
        storageClass: nfs
        accessMode: ReadWriteMany
        size: 1Gi
        volumeSpec:
          nfs:
            server: 10.10.0.1
            path: >-
              /mnt/media/Videos/Movies
