server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: "/var/log/promtail/positions.yaml"

clients:
  - url: "http://192.168.113.10:3100/loki/api/v1/push"

scrape_configs:
  - job_name: nftables_denied
    pipeline_stages:
      - json:
          expressions:
            interface: "oob.in"
            src_ip: "src_ip"
            dest_ip: "dest_ip"
            verdict: "raw.label"
            protocol: "ip.protocol"
            dest_port: "dest_port"
            timestamp: "timestamp"
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - template:
          source: verdict
          template: "{{if eq .Value 0}}'accepted'{{else}}'rejected'{{end}}"
      - labels:
          interface:
          verdict:
      - output:
          source: output
    static_configs:
      - targets:
          - localhost
        labels:
          job: nftables
          __path__: /var/log/ulogd/nftables.json
