---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: applications
spec:
  interval: 5m
  chart:
    spec:
      chart: nzbget
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    #podSecurityContext:
    #  fsGroup: 1001
    #securityContext:
    #  runAsUser: 1001
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "transfer-down"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/nzbget/nord.css"></head>';
            sub_filter_once on;
        hosts:
            - host: &host "nzbget.${SECRET_PRIVATE_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: longhorn
      #downloads:
      #  enabled: true
      #  type: custom
      #  mountPath: /downloads
      #  storageClass: nfs
      #  volumeSpec:
      #    nfs:
      #      server: 10.10.0.1
      #      path: /mnt/media/Downloads/NZB-Usenet
