---
# Source: Administrator Addition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-documents
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: "nfs"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: "1Gi"
  nfs:
    server: 10.10.0.1
    path: >-
      /mnt/media/Documents
---
# Source: Administrator Addition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-coderepos
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: "nfs"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: "1Gi"
  nfs:
    server: 10.10.0.1
    path: >-
      /mnt/media/CodeRepos
---
# Source: Administrator Addition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: "nfs"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: "1Gi"
  nfs:
    server: 10.10.0.1
    path: >-
      /mnt/media/KubePVC/syncthing-data-pvc
---
# Source: syncthing/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: syncthing-data
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: "nfs"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: Administrator Addition
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: syncthing-documents
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: "nfs"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: Administrator Addition
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: syncthing-coderepos
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: "nfs"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: syncthing/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: syncthing-discovery
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    metallb.universe.tf/allow-shared-ip: syncthing
spec:
  type: LoadBalancer
  #loadBalancerIP: "172.21.0.1"
  ports:
  - port: 21027
    targetPort: 21027
    protocol: UDP
    name: discovery
  selector:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
---
# Source: syncthing/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: syncthing-listen
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    metallb.universe.tf/allow-shared-ip: syncthing
spec:
  type: LoadBalancer
  #loadBalancerIP: "172.21.0.1"
  ports:
  - port: 22000
    targetPort: 22000
    protocol: TCP
    name: listen
  selector:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
---
# Source: syncthing/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8384
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
---
# Source: syncthing/templates/common.yaml with administrative modifications
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: applications
  labels:
    helm.sh/chart: syncthing-3.3.0
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/version: "1.18.2"
    app.kubernetes.io/managed-by: Helm
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: syncthing
      app.kubernetes.io/instance: syncthing
  template:
    metadata:
      labels:
        app.kubernetes.io/name: syncthing
        app.kubernetes.io/instance: syncthing
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: syncthing
          image: "syncthing/syncthing:1.18.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: discovery
              containerPort: 21027
              protocol: UDP
            - name: listen
              containerPort: 22000
              protocol: TCP
            - name: http
              containerPort: 8384
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/syncthing
            - name: documents
              mountPath: /var/syncthing/Documents
            - name: coderepos
              mountPath: /var/syncthing/Code
          livenessProbe:
            tcpSocket:
              port: 8384
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8384
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8384
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: syncthing-data
        - name: documents
          persistentVolumeClaim:
            claimName: syncthing-documents
        - name: coderepos
          persistentVolumeClaim:
            claimName: syncthing-coderepos
