# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: kube-system
stringData:
    cloudflare-token: ENC[AES256_GCM,data:Z+gl/XYUI4Tn8BiLRvN3pRA3BUDHwQ9XLGM3sY4CTc4rqmRGLj/ZPw==,iv:dXoGtClDTBQZa48syJt6riWnWF3nkGUeelHTbaT6l8A=,tag:0kcEzxLEICuMJZA0hobZvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-03T18:44:21Z"
    mac: ENC[AES256_GCM,data:JkDGHdVYMgQhVy6TS7T1NB1QrieqeAg1T4QJOZVxGdm7oZbRma5kXqvEsawSlyijXq28CPDrYIfbYOOXup8qkzVLdyL03T5P75XHCHbyYmlde5vjZjiYziWV77CTd+9y1HRfsXSp29ByD/4a9C4aBjmWqepkMJLlJwITSoDWi9w=,iv:JZlL+Lo7ddteZX8Sc8yA9CrMd2q7ByruW100DIc5kl0=,tag:ipzfC5sfCm07L2M/r/P0Jw==,type:str]
    pgp:
        - created_at: "2022-02-03T18:44:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2SjgiqYlWcgAQ/9HHkH7+AmQAsTolinYZRunR7Rylz1Dbpse3kK6YLX5jks
            dea4RKt52OsMNcnbxKFIMsv0Ip7I88SkJmI4fdHo0rOcjX5DwvsLxV8vHfbs8FqG
            Yoiq26Jlxmrz6SridxempQD0m4mUU7DQtl8VuqquUF1bQJ/r96MvFb9ClOvtZKw8
            Df2ixBmLF3JJGDYWCkPN7CS3Y21AvdI9pF4i2HwODOlWcUhHEaiUCpxZ/JTAezou
            bGOAT1Lx635/ybljBHiUrT4xVJAwzfh4Zx8vdlrmX7mHDNMXcG3YDBLbRZa0rEBa
            by4/LoG3QlLp9M0OIPVTkvbKe7wYz86nm8VPCfqOq96LQvLKle9qT1ASYcOPu5oI
            2cQ96wvO3iQH9qkiYRQ+td9KGQWPKXFeCTxS8gyKRFLJW6ZbhiEAt4pEpIr5n3dK
            8jcArQSjhoPboXpX74HZEUMGtQNqDE9K1QjJgTV5lA/cVTFkMXnHP3su4RBM6o+f
            7jTkFgVfR4KrljqGo1dK0FiEctQpe6cTiwPXruQkxIpEYtu5NH5fM3fgjuAHSzPv
            d2GJcKwHCuYoDwnqmIvYPwl+XKxkOw8XA3X3lPJ/MSK2DIpzDw560evtbG1ExebC
            jqhg9nn7E+Dbq2xaj1GHgMHUoY22nmUOCTzVHKn1Hy8LuNgfk0YwWPm6LGQD2NDS
            XAFCShz63PYdRUbCWyl1JgNE1Pb9zDcnlizpoRW6eFcpkCv0EJLZvua3EhTLvzZa
            QovaEEVu3/EquvMppbe8yARS/AqiDsRM62MdDIGJIBG1iAdMhZ4AjhGL2/md
            =g8CS
            -----END PGP MESSAGE-----
          fp: 0B7275A133DEA971175DF634F14FAC73727DD99B
        - created_at: "2022-02-03T18:44:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAzzcuyRg0rbSAQv/fWW/Ubg4CItzAIk2sYxGUK7sk/GiMoQI9K4qlmKAlnPH
            okrnHZcN/D2VPQS8JbuSqLlRXRZMBPqvZlMbZ3n/6KBjf5dnRAggLPnMAuZv4HM4
            gpaUCiF6rlK1D2N19EvcF00pxLNMiyFSHuatMGq5RbZRlj6yXjo28VHoCA794DkO
            7pjnr0Sw2CWDRfqsiu45SDrlmh6l1HIbsNDpfG567vi5ajcLkO3MKnSJljwAVbdO
            PPQg71alYLIHIsmdVRedHQov0x0TPbfnUlfPABnoRLtIuEV4FLf9h8hCuYLAw/na
            etorOtGktRoqvxK7UI0eNxJOt+K2u+zGcAciACCsd8Lly6TKI+UvaNtjOARsvIE6
            ykISRtYYxSDe2QIdHgOKPeta1qhHSAu3rkIcCOCqg6QamiDKRfPQUaovMNEe26D6
            tIW0343wE/6VkXuxkwJdCJsnJArhhwtIK5oTy0RvXGrjG5FRziLmIywmdnpgqeVN
            1U3wN2ZYZV0nQDzwwe840lwBw17nHuWbNFw+pPz27bKTmHs4p7H1KFHnueAFtpni
            J9SbZ9xokz2vIrX8XJYmklkSQP0JFCvJW6ee/ua+2jy3Dkdqp5M2wf9rubORzgK/
            fkVSpAwOtITcxkKzdA==
            =BHbM
            -----END PGP MESSAGE-----
          fp: 90AB4A0FF0F17A5CAC2AEABAA538A7E3EC07999A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
