---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: eperry
spec:
  interval: 5m
  chart:
    spec:
      chart: syncthing
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  timeout: 30m
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "172.21.0.1"
        annotations:
          metallb.universe.tf/allow-shared-ip: syncthing
      listen:
        type: LoadBalancer
        loadBalancerIP: "172.21.0.1"
        annotations:
          metallb.universe.tf/allow-shared-ip: syncthing
      discovery:
        type: LoadBalancer
        loadBalancerIP: "172.21.0.1"
        annotations:
          metallb.universe.tf/allow-shared-ip: syncthing
    podAnnotations:
      configmap.reloader.stakater.com/reload: "syncthing-config-file"
    persistence:
      data:
        enabled: true
        exsistingClaim: syncthing
