---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
  namespace: eperry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeName: syncthing
  storageClassName: longhorn
  volumeMode: Filesystem
