apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secret-decryption
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  force: false
  interval: 10m0s
  path: ./kubernetes/fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
