# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:r16yT3WoulBQNqTYDBVE8PlfecduDyQ=,iv:kFeK95+RKZzAiybB1/jazxTaoHYIgd3A+fOK5Ke2TVM=,tag:1dLW5HcFoOqUFoXaAVyAPw==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:fIfvTi/ceRtin+g6Lgk=,iv:vqNV9NihSvCUbXPYGV4XvkD1998HjFkebf4qasZ4K8s=,tag:RdaUJ1QU8s1iA6vhNUmVxg==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:Y6yjnIc7Vk+MHWYvqAkSItHL,iv:nxe1R8XrP2Q9ScxHpqV+1IWQB2sHBvi/i9G0kkhcKkY=,tag:sEr2A9KI1Jfsjull/qGnDw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:vnpg/SPBSi0Pwk/PC7CSjkYR2xhjfoJHig==,iv:Cza8TOVdyUYHo6E3LHjQB/8NkyWPZaoHqz0O/Z+kseA=,tag:X4ObfiFzy4zh/ApKm2YKSw==,type:str]
    SECRET_BGP_PASSWORD: ENC[AES256_GCM,data:U9Sgx+I74nBDfKpTHHT62tboucURl7mRpQ==,iv:ZcgLwTD4R4oCrqv1UfMAgkvvQXVQx33HjBgzKJRjY2k=,tag:wOSp1npkXVJ5bj2gNJ4sCQ==,type:str]
    SECRET_OPENVPN_STRING: ENC[AES256_GCM,data:QKT9t46VB+o6JD5v/LS4IlYxjTPb,iv:Nypyl8Oa0Y8vbw549Tp0kAmWW4KqxJiPAXI8DtfYKfI=,tag:CnfxpqJekGfA4wfFlWuCRQ==,type:str]
    SECRET_OPENVPN_PORT: ENC[AES256_GCM,data:7zoeSBE=,iv:PZ2IM+xVagkgU9IugY5HuyYLz4E43Mvu+lQrPqyp578=,tag:2svlMcoEDykHzrI/ReMunA==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:qHJsQQfOcjEs+9EEhk5VXkwnO31ey4P9r2WmMZbS071Esr7z6Gp6keeUFV1Cd2Fed82kVfC8JDUwUTJuYYSyE0ZdFWmGQ1t5aPa0jm51E5I2nxudanLT054UrRtN0CBpGE43kKNJEsXkcq6HjOEBuUDK5hqhvEsPK2Ev,iv:SkddNV755sCqB3vl01ttlunSM1sjUMNLoRvr+gE0v80=,tag:vxeKEtqogxig3PodB5X5Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-31T16:20:22Z"
    mac: ENC[AES256_GCM,data:97JLohJIddqfMSPuvY2LTvB2jn9sk5xgZdBnLhkl/KYJvFyj071pB6xqsg3PscGsftMTDrBYEe6qtHN0P9LkmC89kqlsJqlfPSVsJ2vocqG8S/h+AFbAwga39qzNfhL7VEcfH6mo9i0oV8bmbadlD+VMXfTbVztOyNnQ3XI3JQw=,iv:vrx/5jBXFuvI+VX0rSgf+Z18NtVS0aSEZa8tSSa8lxk=,tag:ov81ENmG1jCyj2uDSCcwYA==,type:str]
    pgp:
        - created_at: "2022-01-31T16:20:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2SjgiqYlWcgAQ//TgvhpQYMuvuQSn6MhgUioXc0fQGsJK46PbXbsAIM93Ew
            iZDsOmEQWh/243aYfEpNGnnxbn/0ZYUZh3tyCkp0qasHw7rc2olhOPEjmbZmpcVm
            VJQufeSAhhtFW19FIHmYrZ8NLP630yPxVTDLP2AWcU4kFDuBUzCDMZGD+ZDQWbbA
            Xxnwz2OSA+a7dkgUT6yeBm+VPO7ThegtFXpjRp7UqXqEjX+T3WxqWIac8/X3NBvj
            YXDVAwo0NHoTrko4AQ67d1D6Hbx12VYtskduY/HgrZH7RHLXVzJ9qby3Qk2FU6nC
            JNntx81wfP5d6RWgab4wcuadqMx+zLyHbYsRYlX2RBvpT8Cr/R3XpZzzSA7JFKFQ
            wHsB3u2HBsY03CPftiyDZJpS84kdWSDvFGcX1BIV+70qnypqGxk4kiZ4XD7X++hy
            o9KF+A0cCynl2TYBOgfkDc4kzisSHZqrvvuc5kAK5R4i7f7OULUQbDV9JzqWazjS
            mZQrmHG9cuETx4PQiWfNpIM0agdflhRH6hIDWx6y1Mdn+Ejo2Ju2Kcpu0fGYizad
            RWDyRe9U9R6V0En+Dh1huWNMfnofj5H6BYSM4qcmzhW/vK7rlPVbyYHG7Ke68OOy
            yi4nudIsIVIn/aIL0+Fx08f6OVjdHiWCY17p9rFDRO0I0Z6cO7XBGAhwNo1fKPzS
            XgF3NiUAJYK/nRRq8M7MaWeX5ISPAo66j+jSjMS1mQ53SDqDUW5AJqWV9zy3Ed+4
            OzwuhlZildoHKg0cpaL7dcSMVPwfPhs+ZMkiK61747DhhF3Lepy3frsIVpb7hXk=
            =ffu+
            -----END PGP MESSAGE-----
          fp: 0B7275A133DEA971175DF634F14FAC73727DD99B
        - created_at: "2022-01-31T16:20:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAzzcuyRg0rbSAQv/VF8N+MsQoZQGe3CyDzfpdzEe812LybE3zNHi01XIqJjy
            dh9qNWAidOU4rdEEZlRQo2YmsptwQXVX+S7q+skgoUYoPjdbmCB4XVZS33wcwvIS
            3msgbkBDoBMVwHpp0dED3F6OGDlBuQU/m+Dajji+DCPrJq54XsuoeNW2bSYPfLFT
            a2q2jA9ahgeAndjACEOMXwHbRZpccOevdYiofyQUaN6eTYh92n71Hb9Tk1J9pDx2
            5liQmHpbNG4+AV13oAWsFskOzRsBqYt6eyOlVOwQ41vnlVd0ZgOH+CUwVvQEY9aV
            DcSZGDHH6sEL+DO/W9FtoXwLmzt/fWHgJtqhOyNDj9va+cImhGccGwkS3bRPOzkm
            RZTI2VaXNYBX7m2nUUUSQR1AuRwQwVz7q0RJBPQ1Z+JjIit0C30cvMxAblI915+b
            2oMkV8NSNENKV3diVw6y7FCE5AGDo0eDfJJY5EWcnUGWMLWnMVaU9VtyDCMA6x5v
            vpajW8HC+0K3JoN6P4rD0l4B3T2kDs17/FGMuAz+WqEKRfpO285Wwhvn4BYz/zxE
            poMp5z0xts7Vw3vbagHLDQlTObkgoUYGKdPveYC24Tyo7NDo9pOD0iPYSlJUWMok
            XCp+/KXWU9UgDGdkdud7
            =Td4h
            -----END PGP MESSAGE-----
          fp: 90AB4A0FF0F17A5CAC2AEABAA538A7E3EC07999A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
