---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads-vpn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      setGateway: "true"
    persistence:
      config:
        enabled: true
      downloads:
        enabled: true
        type: custom
        mountPath: /downloads
        storageClass: nfs
        accessMode: ReadWriteMany
        volumeSpec:
            nfs:
                server: 10.10.0.1
                path: /mnt/media/Downloads/Torrent
      tvseries:
        enabled: true
        type: custom
        accessMode: ReadWriteMany
        mountPath: /media/TVSeries
        volumeSpec:
          nfs:
            server: 10.10.0.1
            path: >-
              /mnt/media/Videos/TVSeries
    initContainers:
      wait-for-gateway-mutator:
        image: k8s.gcr.io/busybox
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          while [ $(curl -sk "https://vpn-gateway-pod-gateway-webhook.network-components.svc.cluster.local:8080/wh/health") != '{"ok":true}' ]; do
            sleep 15;
          done
