---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rtorrent-flood
  namespace: vpn-redirect
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: rtorrent-flood
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    hostname: torrent # needed for an static IP
    podAnnotations:
      setGateway: "true"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "172.21.0.2"
        ports:
          http:
            port: 80
            targetPort: 3000
    persistence:
        config:
            enabled: true
            storageClass: nfs-client
        downloads:
            enabled: true
            type: custom
            mountPath: /downloads/download
            storageClass: nfs
            volumeSpec:
                nfs:
                    server: 10.10.0.1
                    path: /mnt/media/Downloads/Torrent
    initContainers:
      wait-for-gateway-mutator:
        image: curlimages/curl
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          while [ $(curl -sk "https://vpn-gateway-pod-gateway-webhook.network-components.svc.cluster.local:8080/wh/health") != '{"ok":true}' ]; do
            sleep 15;
          done
    addons:
      netshoot:
        enabled: true
