---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: documents
spec:
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  timeout: 30m
  values:

    image:
      # -- image repository
      repository: nodered/node-red
      # -- image tag
      tag: 2.1.4
      # -- image pull policy
      pullPolicy: IfNotPresent
    
    # -- environment variables. See [image docs](https://nodered.org/docs/getting-started/docker) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: UTC
      # -- Node.js runtime arguments
      NODE_OPTIONS:
      # -- Setting to `true` starts Node-RED with the projects feature enabled
      NODE_RED_ENABLE_PROJECTS:
      # -- Setting to `true` starts Node-RED in safe (not running) mode
      NODE_RED_ENABLE_SAFE_MODE:
      # -- Location of the flows configuration file.
      # If you set `FLOWS: ""` then the flow file can be set via the `flowFile` property in the `settings.js` file.
      FLOWS: flows.json
    
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 1880
    
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "gears"
        hosts:
          - host: &host "node.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    securityContext:
      runAsUser: 1001
      runAsGroup: 0
    
    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        mountPath: "/data"
        size: 4Gi

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
