- name: Install fail2ban
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - fail2ban

- name: Create logfile for the daemon
  ansible.builtin.file:
    path: /var/log/fail2ban.log
    state: touch
    mode: 0644
    owner: root

- name: Configure F2B Jails
  ansible.builtin.copy:
    content: |
      [DEFAULT]
      banaction          = nftables[type=multiport]
      banaction_allports = nftables[type=allports]
      
      bantime.increment    = true
      bantime.overalljails = true
      
      ignoreip = 127.0.0.1/8 ::1 {{ fail2ban_ignoreip }}
      
      [sshd]
      enabled = true
    dest: /etc/fail2ban/jail.local
    mode: 0644
    owner: root
  notify: fail2ban

- name: Configure F2B NFtables integration
  ansible.builtin.copy:
    content: |
      [Init]
      table          = fail2ban
      chain_priority = -150
      blocktype      = drop
      chain_hook     = prerouting
    dest: /etc/fail2ban/action.d/nftables-common.local
    mode: 0644
    owner: root
  notify: fail2ban

- name: Ensure /etc/systemd/system/fail2ban.service.d exists
  ansible.builtin.file: path=/etc/systemd/system/fail2ban.service.d state=directory

- name: Configure systemd unit override
  ansible.builtin.copy:
    content: |
      [Unit]
      After=nftables.service
      Requires=nftables.service
      PartOf=nftables.service
      
      [Service]
      PrivateDevices=yes
      PrivateTmp=yes
      ProtectHome=read-only
      ProtectSystem=strict
      ReadWritePaths=-/var/run/fail2ban
      ReadWritePaths=-/var/lib/fail2ban
      ReadWritePaths=-/var/log/fail2ban.log
      ReadWritePaths=-/var/spool/postfix/maildrop
      ReadWritePaths=-/run/xtables.lock
      CapabilityBoundingSet=CAP_AUDIT_READ CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW
      
      [Install]
      WantedBy=multi-user.target nftables.service
    dest: /etc/systemd/system/fail2ban.service.d/override.conf
    mode: 0644
    owner: root
  notify: fail2ban
