apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grist
  namespace: documents
  labels:
    app.kubernetes.io/name: grist
    app.kubernetes.io/instance: grist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
  storageClassName: "longhorn"
