---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
