# -- { Terraform provisioning } -- #
virtual_machine:
  - name: "kubernetes"
    prefix: '172.22.3.0/24'
    vm:
      - name: 'x86-server-a.{{ domain_private }}'
        ip: '172.22.3.10'
      - name: 'x86-worker-a.{{ domain_private }}'
        ip: '172.22.3.15'

# -- { BPG Peering with BIRD } -- #
bgp_state: present
ibgp_peers:
  - name: rpi-edge-fw
    ip4_cidr_address: "172.22.0.1/25"
  - name: kvm-legion
    ip4_cidr_address: "172.22.0.4/25"
  - name: amd64-server-aa # This host is on kvm-xenia
    ip4_cidr_address: "10.10.0.5/24"
    bfd: false
  - name: amd64-worker-00 # This host is on kvm-xenia
    ip4_cidr_address: "10.10.0.10/24"
    bfd: false
  - name: arm64-worker-00
    ip4_cidr_address: "172.22.0.59/25"

# -- { Prometheus Node exporter } -- #
prometheus_version: latest
prometheus_targets:
  node:
  - targets:
    - localhost:9100

# -- { NFS Configuration } -- #
nfs_server: true
nfs_directories:
  - /mnt/media/KubePVC
  - /mnt/media/CodeRepos
  - /mnt/media/Documents
  - /mnt/media/Downloads
  - /mnt/media/Pictures
  - /mnt/media/Videos
  - /mnt/media/Music
  - /mnt/media/Books
nfs_clients:
  - 10.10.0.5/32
  - 10.10.0.10/32
  - 172.22.0.59/32
  - 172.22.0.60/32
