---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: applications
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "172.21.0.3"
        ports:
          http:
            port: 8096
    persistence:
      config:
        enabled: true
        storageClass: nfs-client
      tvseries:
        enabled: true
        type: custom
        mountPath: /media/TVSeries
        volumeSpec:
          nfs:
            server: 10.10.0.1
            path: >-
              /mnt/media/Videos/TVSeries
      movies:
        enabled: true
        type: custom
        mountPath: /media/Movies
        volumeSpec:
          nfs:
            server: 10.10.0.1
            path: >-
              /mnt/media/Videos/Movies
