---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_PUBLIC_DOMAIN/./-}"
  namespace: kube-system
spec:
  secretName: "${SECRET_PUBLIC_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_PUBLIC_DOMAIN}"
  dnsNames:
    - "${SECRET_PUBLIC_DOMAIN}"
    - "*.${SECRET_PUBLIC_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_PRIVATE_DOMAIN/./-}"
  namespace: kube-system
spec:
  secretName: "${SECRET_PRIVATE_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_PRIVATE_DOMAIN}"
  dnsNames:
    - "${SECRET_PRIVATE_DOMAIN}"
    - "*.${SECRET_PRIVATE_DOMAIN}"
