---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - crds.yaml
  - helm-release.yaml
  - prometheus-rule.yaml
  - letsencrypt-production.yaml
  - certificate.yaml
