---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - netshoot.yaml
  - reloader
  - longhorn
  - nginx-ingress-controller
  - kube-prometheus-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-charts
  path: ./kubernetes/infrastructure/cert-manager
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-cert-manager-certs
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-charts
  path: ./kubernetes/infrastructure/cert-manager-certs
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: cluster-settings
