# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:/9WcislEiQVDF4bvws93qPiEoUr86Ic=,iv:7iMC2UZsK6MVRKmKg7BvZGK2IOZZuXi96OeV6+6wnB0=,tag:5hPxbOrMHWtvNCbimsCzRA==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:ow6Q3WI1yCOO435kO8k=,iv:xoSz5lVsM7HfZbDoNl1gH4TXoo1WjnwCLE+DdMoOmVI=,tag:FpelRkV8TQauhTBmMJ3x3g==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:fP1MtBpemgua7Jf8tGURFVF+,iv:UdqEYY6lUS5peT533ajoMi7NAa+dHjHIKACxwsP9kWc=,tag:62hIbr2xDkvuvI0t4JHOlg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Nhi5+ghjDKzr5vhw11YdlIwsmJhOKNXY+Q==,iv:P/KhWfg0i0rhNTnnpYBkD5JdK1IqHXdIhINSKUjTldI=,tag:340uJ/b778CYbbClG86Spw==,type:str]
    SECRET_BGP_PASSWORD: ENC[AES256_GCM,data:1dNMKdKcSl8qm0sHxanpahas+IDO6wBdQw==,iv:CZgXYNPEuwobT/fi4y5UQiFtOsXzXLzE8ioROMDCNHc=,tag:uoi9L+/d/ABYjPRt6WnZBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-13T13:19:17Z"
    mac: ENC[AES256_GCM,data:uuVYo297w2Iya7JF99kowG0dGaacVG4D5stgKtbYrAeeYuaK+q0DJaayXdCT3tOdl8PaE7P5fuOw6wbQtztDaY8LBLorhuKFDJlhghK2SdpPPVyXrEe2ioIxU+cMI9c6nDZ68WLfnneQj0Yo4SnqAzFJvEplOLwUrUrNVQKNBFc=,iv:ObtsKFiY48HmUcLqQi1wkHqEVJGshSHdl8q8usqUYqI=,tag:4lVn5IjW6NJg5Y8ORGh8Bw==,type:str]
    pgp:
        - created_at: "2022-01-13T13:19:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2SjgiqYlWcgAQ/9HIumu3MU5iPpgphwZ4Ky6MloVHx9hc3F6t37wxSkxZlm
            NmXs0dgxYYdtZbmYjAnegy1A07ArZVxUtpzJRsjrwpNvFYvvpN4sxsSPZf7wrhCj
            zxZH8QRKOP/bDiy6vgeyDAjZ8ZkvY7Y87eViDvXrpw5MNdb9OfT3Ii6YmTwuK6ef
            95pesgHdZZgLxgPT6YE0wceCq1owoBoLxOXT9+ce/0t7AKQGVZffwYqeXwhopRFZ
            UgZgjCbaB9oAmL9W1OLH8jBcsbe55VRBatcYloHxCFu1nDP87bWX0pS/GWpSXHBO
            idxl8j8M/KESepGVfiNbjMSwN14vVXnL8VbYMAlFlrDGUGHyeVZL4BX0vKx5zNB6
            uY8PHHc+252lfBpqPcoG2D7oS1QqUbspp4/5chL84bisfFUVHHhxoqGEBaT007xb
            A3Hn0PpHJq1a67ZSQLZ5o7COpOC3fX3KwjetuVGvyglvgaAC73/J9+poZD+o6IZ7
            8h+GarR8nbOkn+dLP/HLj9IjqO0+EgfXU9gCF/Uc6FUXNrweGu22Z8G/eUaz3SXr
            tv/8GziKeA8iJ8HExtI9pZV2VEyF9HjVBXZIvKuTBnEdf2b6QnR2b3pSyaAxOzVT
            oGilp/CkIDNveqKn3qveXUB3e3Fjt/2RniicM+mxePZ+zG99fLY76qDLJRCnSRvS
            XAH7NBthfDibjUXIBZIIn1CBJSETnZC13Bz6LXa0oh0x7lb5jEdMittD3UBqd+ys
            mcu5VggS8WmAeldKQP3t2jpA2yG2uUkxQ+voxmcpb4LQ4vxGiTchkpN4aH3q
            =XvtI
            -----END PGP MESSAGE-----
          fp: 0B7275A133DEA971175DF634F14FAC73727DD99B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
