---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/namespaces
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
