---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: documents
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: open-8gears-charts
        namespace: flux-system
      interval: 5m
  timeout: 30m
  values:
    extraEnv:
      TZ: "${TIMEZONE}"
    persistence:
      enabled: true
      size: 4Gi
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "gears"
      hosts:
        - host: &host "n8n.${SECRET_PUBLIC_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
