---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: nzbget
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    podSecurityContext:
      fsGroup: 1001
    securityContext:
      runAsUser: 1001
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "transfer-down"
          #! Forward Authentication breaks lunasea.
          #nginx.ingress.kubernetes.io/configuration-snippet: |
          #  proxy_set_header Accept-Encoding "";
          #  sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/nzbget/nord.css"></head>';
          #  sub_filter_once on;
          #nginx.ingress.kubernetes.io/auth-url: |-
          #  http://ak-outpost-authentik-embedded-outpost.applications.svc.cluster.local:9000/akprox/auth/nginx
          #nginx.ingress.kubernetes.io/auth-signin: |-
          #  https://nzbget.${SECRET_PRIVATE_DOMAIN}/akprox/start?rd=$escaped_request_uri
          #nginx.ingress.kubernetes.io/auth-response-headers: |-
          #  Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          #nginx.ingress.kubernetes.io/auth-snippet: |
          #  proxy_set_header X-Forwarded-Host $http_host;
        hosts:
            - host: &host "nzbget.${SECRET_PRIVATE_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: longhorn
      nzbget-config:
        enabled: true
        type: custom
        mountPath: /config/nzbget.conf
        subPath: nzbget.conf
        volumeSpec:
          configMap:
            name: nzbget-config-file
      downloads:
        enabled: true
        type: custom
        mountPath: /config/downloads
        storageClass: nfs
        volumeSpec:
          nfs:
            server: 10.10.0.1
            path: /mnt/media/Downloads/NZB-Usenet
