---
- hosts:
    - k3s-master-nodes
    - k3s-worker-nodes
  gather_facts: true
  become: yes
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  roles:
    - k3s.kubernetes
  tasks:
    - name: Install ISCSI Utils
      community.general.rpm_ostree_pkg:
        name:
          - libiscsi
          - libiscsi-utils
          - iscsi-initiator-utils
