#- name: "Send Common configuration to all systems"
#  hosts: all
#  become: true
#  roles: 
#    - common

- name: "Configure edge firewall"
  hosts: rpi-edge-fw.int.zynthovian.xyz
  become: true
  roles:
#    - sshd_mfa
    - bird
#    - cloudalchemy.prometheus
#    - patrickjahns.promtail

#- name: "Configure on-site hypervisors and deploy VM's"
#  hosts: kvm_hypervisors
#  become: true
#  roles:
#    #- kvm-libvirt
#    #- terraform
#    - nfs
#    - bird
##    - cloudalchemy.prometheus

#- name: "Deploy k3s environment on-site"
#  ansible.builtin.import_playbook: kube-deploy.yml
