---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: applications
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io/
      chart: authentik
      version: 2022.4.1
      sourceRef:
        kind: HelmRepository
        name: goauthentik-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "account-lock"
      hosts:
        - host: &host "authentik.${SECRET_PUBLIC_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    nodeSelector:
      kubernetes.io/arch: amd64

    authentik:
      # -- Log level for server and worker
      log_level: info
      # -- Secret key used for cookie singing and unique user IDs,
      # don't change this after the first install
      secret_key: "${SECRET_AUTHENTIK_COOKIE_KEY}"
      # -- Mode for the avatars. Defaults to gravatar.
      avatars: gravatar
      
      postgresql:
        password: "${SECRET_AUTHENTIK_DB_PASSWORD}"

    postgresql:
      # -- enable the bundled bitnami postgresql chart
      enabled: true
      postgresqlPassword: "${SECRET_AUTHENTIK_DB_PASSWORD}"
      image:
        repository: postgres
        tag: 14.2
      persistence:
          enabled: true
    redis:
      # -- enable the bundled bitnami redis chart
      enabled: true
      architecture: standalone
      image: 
        repository: redis
        tag: 7.0.0
