---
- name: Restart and enable dhcpd systemd service
  ansible.builtin.systemd:
    name: dhcpd.service
    state: restarted
    daemon_reload: true
    enabled: true
  listen: "dhcpd"
  become: true
  when: dhcpd_state == 'present'
  
- name: Stop and disable dhcpd systemd service
  ansible.builtin.systemd:
    name: dhcpd.service
    state: stopped
    enabled: false
  listen: "dhcpd"
  when: dhcpd_state != 'present'
