# Ansible override vars
ansible_host: 172.22.0.1

# Role Options
ssh_mfa_bypass_trusted: true
ssh_mfa_state: present

# -- { BPG Peering with BIRD } -- #
bgp_state: present
ibgp_peers:
  - name: kvm-xenia
    ip4_cidr_address: "172.22.0.3/25"
  - name: kvm-legion
    ip4_cidr_address: "172.22.0.4/25"
  - name: amd64-server-aa # This host is on kvm-xenia
    ip4_cidr_address: "10.10.0.5/24"
    bfd: false
    multihop: true
  - name: amd64-worker-00 # This host is on kvm-xenia
    ip4_cidr_address: "10.10.0.10/24"
    bfd: false
    multihop: true
  - name: arm64-worker-00
    ip4_cidr_address: "172.22.0.59/25"
  - name: amd64-server-b5915c
    ip4_cidr_address: "172.22.0.10/25"

# -- { Prometheus Node exporter } -- #
prometheus_version: latest
prometheus_targets:
  node:
  - targets:
    - localhost:9100

# -- { Loki log exporter } -- #
promtail_config_positions:
  filename: "{{ promtail_positions_directory }}/positions.yaml"
  sync_period: "60s"
promtail_config_scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
#    - targets:
#        - localhost
#      labels:
#        job: nftables
#        __path__: /var/
