- name: Install python and tar
  ansible.builtin.dnf:
    name:
      - tar
      - python3
    state: present

- name: Configure sysconfig to read the main file from /etc/nftables
  ansible.builtin.copy:
    content: |
      include "/etc/nftables/main.nft"
    dest: /etc/sysconfig/nftables.conf
    mode: 0644
    owner: root
  notify: "reload nftables"
  when: nftables_state == "present"

- name: Template NFTables configuration
  ansible.builtin.template:
    src: "{{ nftables_config_file | default('templates/generic.nft.j2') }}"
    dest: /etc/nftables/main.nft
    mode: 0644
    owner: root
    validate: /usr/sbin/nft -c -f %s
  notify: "reload nftables"
  become: true
  when: nftables_state == "present"

- name: Cleanup NFTables
  ansible.builtin.file:
    state: absent
    path: /etc/nftables/main.nft
  notify: "reload nftables"
  when: (nftables_state|default('absent')) != "present"

- name: Include blackhole
  ansible.builtin.include_tasks: blackhole.yaml
