---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: open-8gears-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://8gears.container-registry.com/chartrepo/library/
  timeout: 3m
