---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 1
      extraEnvs:
        - name: TZ
          value: America/New_York
      service:
        externalIPs:
          - "172.21.0.0"
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: >-
          401,403,404,500,501,502,503
        enable-brotli: "true"
        forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
      metrics:
        # TODO: Investigate what this does and its implications
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
          namespaceSelector:
            any: true
        prometheusRule:
          enabled: false
      extraArgs:
        default-ssl-certificate: "kube-system/${SECRET_PUBLIC_DOMAIN/./-}-tls"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: ingress-nginx
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      resources:
        requests:
          memory: 250Mi
          cpu: 100m
        limits:
          memory: 1000Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.16.0
      extraEnvs:
        - name: TEMPLATE_NAME
          value: ghost
        - name: SHOW_DETAILS
          value: "false"
