---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: sandbox
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_PUBLIC_DOMAIN/./-}"
  namespace: network-components
spec:
#  secretTemplate:
#    annotations:
#      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
#      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kasten-io"
#      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
#      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kasten-io"
  secretName: "${SECRET_PUBLIC_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_PUBLIC_DOMAIN}"
  dnsNames:
    - "${SECRET_PUBLIC_DOMAIN}"
    - "*.${SECRET_PUBLIC_DOMAIN}"
