# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:LRA4585HK2rIWUhUZZ7pWa9j6mSnCELsstLYsE2X9IPgUyRYbcD0cQ==,iv:mEGnIeCOqL6oMSWtbo0zNPrZbiL77g7VUSQufOWqT1E=,tag:uoEEW8QW9kSI7LgNGNYwZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-03T12:55:10Z"
    mac: ENC[AES256_GCM,data:WL8Kkq2KLe6CL4YxeR/suvmlWwbi/CPsHoqDlmWCbzysXNikdutmEw4d0qJEW16GRFzmJzrWjNCRnE46nL+IMYI2BYvEMJBLVKIh4qGAyZm74+B18i1QZdUn0+Qw/3cuke4bo6U7noHgon/gDgnpAU59sZjhaD4wdhyLO26PRZ0=,iv:kDnvq0xrPOU1X9CcEG9QPvmJaR74/ILXYyv852aM+xI=,tag:09A5OUeGt8OVyvpQzQ5iCA==,type:str]
    pgp:
        - created_at: "2022-02-03T12:55:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2SjgiqYlWcgARAAntIoQFhgKMU/H9u+7gNydgQiXbjR44vOBmk2+runOIk0
            AXiCbnNH6EBe+UjTayu76vPHWqW/MogWWHgm2OOJ9W7JNVbU9L1TfaaNGT65ls1k
            1Xi6p083kJOEQwtjDZcuL6ILDoTewHiE01MWXrL3KZlf6p/6bMeqZG4YQerIudTX
            JQkukZshTccZ06SBTGUM/dr1czT1cMB9MNETx7CDT7q0eCqYBPiCda2qiJb52ICE
            SMs/ZP1jOFs6SvQ6dP3anmPFTpqAJIPIq7FEv577mdV6T2F+x6AQGb3dasZx0IeK
            x3eegX/4Ofvkg3IXBTnrt4mfaZWkwOLtHExT5j0d2fwfJhP1K9Jpf8sNFkH1CkQ8
            sF8nTthLhHgwxdDFO/wCPPOmFg/7ds3jfz3Z2We3HYhYcmelKHqSm9tfCGfImckr
            BTZP0REeRqMhrpyJrXOX6Dzfnm1jtXmeStyQHQWiJfh6ZL2bzJEHK9FLxvNLELVb
            Qun2WwC5Pu5cwY7YPyUENAY+O9LnjPmHGUqSy12hWmRLzBb0vUjPQLDWxsUruBPf
            c2pyLzQrQbynDcAyeHqdg559PzKsvpH4oP1LJoWVtq5tqEAOwq4H7XX/Dk52DHMF
            eQFhL+VkGlr0b0K9a1vcitEcX7tk3c8PnZTIxnfze8kmXBwCdrDMdnyEViT8H6bS
            XgE+jIq9/imjLPaqo7ygYRn+N9NK6kAemLFlxo5fImgxsutQDZotgIj5aGwUvJSv
            BMG3WtpVNog4q1nNSCKJuQHWgzzadUL4NM48TjzEAgeKB2qztJ0RX13Xf9+e3OM=
            =YYDb
            -----END PGP MESSAGE-----
          fp: 0B7275A133DEA971175DF634F14FAC73727DD99B
        - created_at: "2022-02-03T12:55:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAzzcuyRg0rbSAQv/SLfO2AhiFnRFK1pfgcBfmyi7KZ5M16QKf5POgwGk2Cuv
            upTH5JQn8yJkC/WcaxBAwj/HAP0A1/yObHG0UmmvKLf4cnZA7ysMeaR8YLgLJhjA
            bNnmtK/61QPkx45fHOyMrEBvxpvQH/j6X73GJL/X1jp52M4zCDetfhMssmxTEKZd
            C9P6K2ov3sUE9MduRYm9G5YE9NvBXdvCPCx3olEmEd6rwkhuEZ5BXwiJSIJqheeE
            F+SsyZuN+Tn8idu9I/unWTkzV8PDn6ywZmX66MXQev9/dYDcvZbWKJMb20EjjjaH
            Rr5JmSIhH5gQhVqiPeJN0if38zpB7gisNs/orxCOr1pphKLwpbHvmRBeRdMncwOF
            saCDn6BuZhj5W616bwppi/Q8EmdvK5mDAygsPnYq8M18bVsVRQgV//6fK+TkPdYe
            Y6KioKC6LHCviGWwj+OK6SZGhKLbNX6bQeJY2B0Jgup2/Gvep8/vdOkE1eGhMcAH
            CeQ8KiCFEQ7s6qJvxAwM0l4B1D9Fb3lY7YvbzhFmGBxn19lWXSvwhE3rIjY+E5hJ
            Xmd8/Brr4PKf0ZaP2++1gdVPQGO2/h4j42lellWr2DKbH2obKAiKl6MvY5PG8qKg
            jwJvSDN5LNlixdf2cfDa
            =uHZ0
            -----END PGP MESSAGE-----
          fp: 90AB4A0FF0F17A5CAC2AEABAA538A7E3EC07999A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
