---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kustomize-core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: secret-decryption
  path: ./kubernetes/fluxcd/kustomize-core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
