---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kustomize-core
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/fluxcd/kustomize-core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: cluster-settings
