---
- name: Restart and enable fail2ban systemd service
  ansible.builtin.systemd:
    name: fail2ban.service
    state: restarted
    daemon_reload: true
    enabled: true
  listen: "fail2ban"
  become: true
  when: (f2b_state|default('absent')) == 'present'
  
- name: Stop and disable fail2ban systemd service
  ansible.builtin.systemd:
    name: fail2ban.service
    state: stopped
    enabled: false
  listen: "fail2ban"
  when: (f2b_state|default('absent')) != 'present'
