---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: calibre-web
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-open"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/calibreweb/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "calibre.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    config:
      enabled: true
      storageClass: nfs-client
    books:
      enabled: true
      type: custom
      mountPath: /books
      storageClass: nfs
      volumeSpec:
        nfs:
          server: 10.10.0.1
          path: /mnt/media/Books
