---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-charts
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/helm-charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: cluster-settings
