---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: documents
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  timeout: 30m
  values:
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config:
        enabled: true
        size: 10Gi

    #postgresql:
    #  # -- enable the bundled bitnami postgresql chart
    #  enabled: true
    #  image:
    #    repository: postgres
    #    tag: 14.1
    #  persistence:
    #      enabled: true

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "account-lock"
        hosts:
          - host: &host "vault.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - *host
